extends:
  - recommended

rules:
  operation-operationId-unique:
    enabled: false
    severity: off

  operation-4xx-response:
    enabled: false
    severity: off

  spec:
    severity: warn

  info-license:
    severity: off
