=begin
#Unit OpenAPI specifications

#An OpenAPI specifications for unit-sdk clients

The version of the OpenAPI document: 0.0.4

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::CreditAccountRepaymentInformationResponseData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::CreditAccountRepaymentInformationResponseData do
  let(:instance) { OpenapiClient::CreditAccountRepaymentInformationResponseData.new }

  describe 'test an instance of CreditAccountRepaymentInformationResponseData' do
    it 'should create an instance of CreditAccountRepaymentInformationResponseData' do
      expect(instance).to be_instance_of(OpenapiClient::CreditAccountRepaymentInformationResponseData)
    end
  end
  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["creditAccountRepaymentInformation"])
      # validator.allowable_values.each do |value|
      #   expect { instance.type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "attributes"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
