require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ApplicationForm
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
RSpec.describe 'ApplicationForm' do
  before do
    configure_tests
  end

  describe 'test an instance of ApplicationForm' do
    let(:api_instance) { OpenapiClient::GetApplicationFormApi.new(OpenapiClient::ApiClient.new(configuration)) }

    it 'should get an instance of ApplicationForm' do
      response = api_instance.execute('803451')
      expect(response.data.type).to eq('applicationForm')
    end
  end

  describe 'list application forms' do
    let(:api_instance) { OpenapiClient::GetListApplicationFormsApi.new(OpenapiClient::ApiClient.new(configuration)) }

    it 'should list an instance of ApplicationForm' do
      opts =  { query_params: {"page[limit]": 10, "page[offset]": 0, "filter[email]": 'jone.doe1@unit-finance.com'}}
      response = api_instance.execute(opts)
      expect(response.data[0].type).to eq('applicationForm')
    end
  end

  # describe 'creation of an instance of application forms' do
  #   let(:api_instance) { OpenapiClient::CreateApplicationFormApi.new(OpenapiClient::ApiClient.new(configuration)) }
  #
  #   it 'should create an instance of ApplicationForm' do
  #     request = { data: OpenapiClient::CreateApplicationForm.new(type: 'applicationForm',
  #                                                               attributes:
  #                                                                 OpenapiClient::CreateApplicationFormAttributes.new(
  #                                                                   { email: "john@gmail.com",
  #                                                                     tags: { "purpose": 'tax' } }),
  #                                                               relationships: OpenapiClient::CreateApplicationFormRelationships.new(
  #                                                                 customer: { "data": { "type": 'customer',
  #                                                                                       "id": '851228' } }
  #                                                               ).to_hash).to_hash }
  #     response = api_instance.execute(request)
  #     expect(response.data.type).to eq('applicationForm')
  #   end
  # end
end
