require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ApplicationForm
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
RSpec.describe 'ApplicationForm' do
  before do
    configure_tests
  end

  describe 'test an instance of ApplicationForm' do
    let(:api_instance) { OpenapiClient::GetApplicationFormApi.new(OpenapiClient::ApiClient.new(configuration)) }

    it 'should get an instance of ApplicationForm' do
      response = api_instance.execute('803451')
      expect(response.data.type).to eq('applicationForm')
    end
  end

  describe 'list application forms' do
    let(:api_instance) { OpenapiClient::GetListApplicationFormsApi.new(OpenapiClient::ApiClient.new(configuration)) }

    it 'should list an instance of ApplicationForm' do
      opts =  { query_params: {"page[limit]": 10, "page[offset]": 0, "filter[email]": 'jone.doe1@unit-finance.com'}}
      response = api_instance.execute(opts)
      expect(response.data[0].type).to eq('applicationForm')
    end
  end
end
