require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::CheckDeposit
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
RSpec.describe 'CheckDeposit' do
  before do
    configure_tests
  end

  describe 'test an instance of CheckDeposit' do
    let(:api_instance) { OpenapiClient::CreateCheckDepositApi.new(OpenapiClient::ApiClient.new(configuration)) }

    it 'should create a checkDeposit' do
      request = { data: OpenapiClient::CreateCheckDeposit.new(type: 'checkDeposit',
                                                              attributes:
                                                                OpenapiClient::CreateCheckDepositAttributes.new(
                                                                  { amount: 100,
                                                                    description: 'test',
                                                                    tags: { "purpose": 'tax' },
                                                                    idempotency_key: '1234567890' }),
                                                              relationships: OpenapiClient::CreateCheckDepositRelationships.new(
                                                                account: { "data": { "type": 'account', "id": '2110693' } })).to_hash }
      response = api_instance.execute(request)
      expect(response.data.type).to eq('checkDeposit')
    end
  end

  describe 'list checkDeposits' do
    let(:api_instance) { OpenapiClient::GetCheckDepositApi.new(OpenapiClient::ApiClient.new(configuration)) }

    it 'should get a checkDeposit' do
      response = api_instance.execute('16558')
      expect(response.data.type).to eq('checkDeposit')
    end

    it 'should list checkDeposits' do
      opts =  { query_params: {"page[limit]": 10, "page[offset]": 0, "filter[status]": 'pending'}}
      response = api_instance.execute(opts)
      expect(response.data[0].type).to eq('checkDeposit')
    end
  end

  describe 'update checkDeposit' do
    let(:instance) { OpenapiClient::UpdateCheckDepositApi.new(OpenapiClient::ApiClient.new(configuration)) }

    it 'should update a checkDeposit' do
      request = { data: OpenapiClient::PatchCheckDeposit.new(attributes:
                                                               OpenapiClient::PatchCheckDepositAttributes.new(
                                                                 tags: { "status": "Awaiting Customer Confirmation",
                                                                         "id": "23033b64-38f8-4dbc-91a1-313ff0156d02" })).to_hash }
      response = instance.execute('16558', request)
      expect(response.data.type).to eq('checkDeposit')
    end
  end
end
