require 'spec_helper'

# Unit tests for OpenapiClient::Event
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
RSpec.describe 'Event' do
  before do
    configure_tests
  end

  describe 'test an instance of Event' do

    let(:api_instance) { OpenapiClient::GetEventApi.new(OpenapiClient::ApiClient.new(configuration)) }

    it 'should create an instance of Event' do
      response = api_instance.execute('15543784')
      expect(response.data.type).to eq("transaction.created")
    end
  end
end
