require 'spec_helper'

# Unit tests for OpenapiClient::Fee
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
RSpec.describe 'Fee' do
  before do
    configure_tests
  end

  describe 'test an instance of Fee' do
    let(:api_instance) { OpenapiClient::CreateFeeApi.new(OpenapiClient::ApiClient.new(configuration)) }
    it 'should create an instance of Fee' do
      request = { data: OpenapiClient::CreateFee.new(type: 'fee', attributes: OpenapiClient::CreateFeeAttributes.new(
        { amount: 100, description: 'test', tags: { "purpose": 'tax' }, idempotency_key: "13848484884" } ),
                                                     relationships: OpenapiClient::FeeRelationships.new(
                                                       account: { "data": { "type": 'account', "id": '36099' } }
                                                     )).to_hash }
      response = api_instance.execute(request)
      expect(response.data.type).to eq('fee')
    end
  end
end