require 'spec_helper'
require 'json'
require 'date'
require 'dotenv'

# Unit tests for UnitOpenapiRubySdk::Payment
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
RSpec.describe 'Payment' do
  before do
    configure_tests
  end

  describe 'test an instance of Payment' do
    let(:api_instance) { UnitOpenapiRubySdk::UnitApi.new(UnitOpenapiRubySdk::ApiClient.new(configuration)) }

    it 'should create an instance of BookPayment' do
      request = { data: UnitOpenapiRubySdk::CreateBookPayment.new(type: 'bookPayment', attributes:
        UnitOpenapiRubySdk::CreateBookPaymentAttributes.new(amount: 1000, description: 'test payment', tags: { "test": 'test-tag' }),
                                                             relationships: UnitOpenapiRubySdk::CreateBookPaymentRelationships.new(account: { "data": { "type": 'depositAccount', "id": '27573' } }, counterparty_account: { "data": { "type": 'depositAccount', "id": '36981' } }).to_hash).to_hash }
      response = api_instance.create_payment(request)
      expect(response.data.type).to eq('bookPayment')
    end

    it 'should create an instance of AchPayment with plaid token' do
      Dotenv.load
      request = { data: UnitOpenapiRubySdk::CreateAchPaymentPlaid.new(type: 'achPayment', attributes:
        UnitOpenapiRubySdk::CreateAchPaymentPlaidAttributes.new(amount: 1000, direction: 'Credit', description: 'test payment', plaid_processor_token: ENV['TEST_PLAID_TOKEN']),
                                                                 relationships: UnitOpenapiRubySdk::CreateAchPaymentRelationships.new(account: { "data": { "type": 'depositAccount', "id": '27573' } }).to_hash).to_hash }
      response = api_instance.create_payment(request)
      expect(response.data.type).to eq('achPayment')
    end
  end
end