require 'spec_helper'
require 'json'
require 'date'

# Unit tests for UnitOpenapiRubySdk::Payment
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
RSpec.describe 'ReceivedPayment' do
  before do
    configure_tests
  end

  describe 'test an instance of Payment' do
    let(:api_instance) { UnitOpenapiRubySdk::UnitApi.new(UnitOpenapiRubySdk::ApiClient.new(configuration)) }

    it 'should get an instance of ReceivedPayment' do
      response = api_instance.get_received_payment("8266")
      expect(response.data.type).to eq('achReceivedPayment')
    end

    it "lists ach received payments" do
      response = api_instance.get_received_payments_list({status: %w[Pending]})
      expect(response.data[0].type).to eq("achReceivedPayment")
    end

  end
end