require_relative '../spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::RecurringDebitAchPayment
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
RSpec.describe 'RecurringPayment' do
  before do
    # run before each test
    configure_tests
  end

  let(:ach_instance) { OpenapiClient::CreateRecurringPaymentApi.new(OpenapiClient::ApiClient.new(configuration)) }

  describe 'test an instance of RecurringDebitAchPayment' do
    it 'should create an instance of RecurringDebitAchPayment' do
      schedule = OpenapiClient::Schedule.new(interval: 'Monthly', day_of_month: 3 )
      request = {data: OpenapiClient::CreateRecurringDebitAchPayment.new(type: "recurringDebitAchPayment", attributes:
        OpenapiClient::CreateRecurringDebitAchPaymentAttributes.new({amount: 1000, description: "test pay",
                                                                    schedule: schedule},
                                                                    ), relationships: OpenapiClient::CreateAchPaymentCounterpartyRelationships.new(
        account: {data: {type: "account", id: "27573"}}, counterparty:
          {data: {type: "counterparty", id: "679784"}}
      )
      ).to_hash }
      response = ach_instance.execute(request)
      expect(response.data.type).to eq("recurringDebitAchPayment")
    end
  end
end