require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::Transaction
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
RSpec.describe 'Transaction' do
  before do
    configure_tests
  end

  describe 'test an instance of Transaction' do
    let(:api_instance) { OpenapiClient::GetTransactionApi.new(OpenapiClient::ApiClient.new(configuration)) }

    it 'should create an instance of Transaction' do
      response = api_instance.execute('1060441', '2246427')
      expect(response.data.type).to eq("originatedAchTransaction")
    end
  end
end
