/*
 * Unit OpenAPI specifications
 * An OpenAPI specifications for unit-sdk clients
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreditAccountRepaymentInformationResponseDataAttributes
 */
public class CreditAccountRepaymentInformationResponseDataAttributesTest {
    private final CreditAccountRepaymentInformationResponseDataAttributes model = new CreditAccountRepaymentInformationResponseDataAttributes();

    /**
     * Model tests for CreditAccountRepaymentInformationResponseDataAttributes
     */
    @Test
    public void testCreditAccountRepaymentInformationResponseDataAttributes() {
        // TODO: test CreditAccountRepaymentInformationResponseDataAttributes
    }

    /**
     * Test the property 'remainingAmountDue'
     */
    @Test
    public void remainingAmountDueTest() {
        // TODO: test remainingAmountDue
    }

    /**
     * Test the property 'remainingAmountOverdue'
     */
    @Test
    public void remainingAmountOverdueTest() {
        // TODO: test remainingAmountOverdue
    }

    /**
     * Test the property 'initiatedRepayments'
     */
    @Test
    public void initiatedRepaymentsTest() {
        // TODO: test initiatedRepayments
    }

    /**
     * Test the property 'statementPeriodStart'
     */
    @Test
    public void statementPeriodStartTest() {
        // TODO: test statementPeriodStart
    }

    /**
     * Test the property 'statementPeriodEnd'
     */
    @Test
    public void statementPeriodEndTest() {
        // TODO: test statementPeriodEnd
    }

    /**
     * Test the property 'nextRepaymentDueDate'
     */
    @Test
    public void nextRepaymentDueDateTest() {
        // TODO: test nextRepaymentDueDate
    }

}
